[package]
name = "leonwigley"
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level = 3      # "z" for size, 3 for max speed
lto = true            # Enable Link Time Optimization
codegen-units = 1     # Better optimizations (slower compile)
panic = 'abort'       # Smaller, faster binary if you don’t need unwinding


[dependencies]
axum = "0.7"
tera = "1.20.0"
tokio = { version = "1", features = ["full"] }
pulldown-cmark = "0.12"
serde = { version = "1", features = ["derive"] }
